name: demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: 2.1.0
  get: 4.3.8
  get_storage: 2.0.3
  http: 0.13.3
  flutter_bloc: 7.2.0
  dio: 4.0.0
  cached_network_image: 3.1.0
  infinite_scroll_pagination: 3.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

